// ID cố định của tiện ích
const allowedExtensionID = "cjkigpecplniladpnkkhokfkockhgnho"; 

// Lấy extension_id từ URL
const urlParams = new URLSearchParams(window.location.search);
const receivedExtensionID = urlParams.get('extension_id') || '';

// Dữ liệu các tùy chọn
const guestOptions = [
    { "value": "guest0", "label": "0-Server test" },
    { "value": "guest2", "label": "2-Bongda24h.vn" },
    { "value": "guest4", "label": "4-Cafef.vn" },
    { "value": "guest6", "label": "6-Vnexpress.net" },
    { "value": "guest8", "label": "8-Nld.com.vn" },
    { "value": "guest10", "label": "10-Dantri.com.vn" },
    { "value": "guest12", "label": "12-Baotintuc.vn" },
    { "value": "guest14", "label": "14-Tuoitre.vn" },
    { "value": "guest16", "label": "16-Vietnamnet.vn" },
    { "value": "guest18", "label": "18-Truyenthieunhi.net" },
    { "value": "guest20", "label": "20-soha.vn" },
    { "value": "guest22", "label": "22-vnreview.vn" },
    { "value": "guest24", "label": "24-laodong.vn" },
    { "value": "guest26", "label": "26-vtv.vn" },
    { "value": "guest28", "label": "28-vietstock.vn" },
    { "value": "guest30", "label": "30-thethaovanhoa.vn" },
    { "value": "guest32", "label": "32-dtinews.dantri.com.vn" },
    { "value": "guest34", "label": "34-vov.gov.vn" },
    { "value": "guest36", "label": "36-congdankhuyenhoc.vn" },
    { "value": "guest38", "label": "38-vietnamplus.vn" },
    { "value": "guest40", "label": "40-kinhtedothi.vn" },
    { "value": "guest42", "label": "42-bongdadoisong.vn" },
    { "value": "guest44", "label": "44-vgt.vn" },
    { "value": "guest46", "label": "46-dautuvietnam.com.vn" },
    { "value": "guest48", "label": "48-vietbao.vn" },
    { "value": "guest50", "label": "50-vietnambeauty.com.vn" },
    { "value": "guest52", "label": "52-doisongnet.vn" },
    { "value": "guest54", "label": "54-doanhnhanduongthoi.com.vn" },
    { "value": "guest56", "label": "56-nongthonvaphattrien.vn" },
    { "value": "guest58", "label": "58-docnhanh.vn" },
    { "value": "guest59", "label": "59-roc-taiwan.org" },
    { "value": "guest60", "label": "60-vneconomy.vn" },
    { "value": "guest61", "label": "61-sggp.org.vn" },
    { "value": "guest62", "label": "62-vaticannews.va" },
    { "value": "guest64", "label": "64-" },
    { "value": "guest66", "label": "66-" },
    { "value": "guest68", "label": "68-" },
    { "value": "guest70", "label": "70-" },
    { "value": "guest72", "label": "72-" },
    { "value": "guest74", "label": "74-" },
    { "value": "guest76", "label": "76-" },
    { "value": "guest78", "label": "78-" },
    { "value": "guest80", "label": "80-" },
    { "value": "guest82", "label": "82-" },
    { "value": "guest84", "label": "84-" },
    { "value": "guest86", "label": "86-" },
    { "value": "guest88", "label": "88-" },
    { "value": "guest90", "label": "90-" },
    { "value": "guest92", "label": "92-" },
    { "value": "guest94", "label": "94-" },
    { "value": "guest96", "label": "96-" },
    { "value": "guest98", "label": "98-" },
    { "value": "guest100", "label": "100-" }
];

const userOptions = [
    { "value": "0", "label": "0-Server test" },
    { "value": "1", "label": "1-kenh14.vn" },
    { "value": "2", "label": "2-Bongda24h.vn" },
    { "value": "3", "label": "3-Cafebiz.vn" },
    { "value": "4", "label": "4-Cafef.vn" },
    { "value": "5", "label": "5-Genk.vn" },
    { "value": "6", "label": "6-Vnexpress.net" },
    { "value": "7", "label": "7-voh.com.vn" },
    { "value": "8", "label": "8-Nld.com.vn" },
    { "value": "9", "label": "9-Nguoiquansat.vn" },
    { "value": "10", "label": "10-Dantri.com.vn" },
    { "value": "11", "label": "11-Thanhnien.vn" },
    { "value": "12", "label": "12-Baotintuc.vn" },
    { "value": "13", "label": "13-Techz.vn" },
    { "value": "14", "label": "14-Tuoitre.vn" },
    { "value": "15", "label": "15-Suckhoedoisong.vn" },
    { "value": "16", "label": "16-Vietnamnet.vn" },
    { "value": "17", "label": "17-Autopro.com.vn" },
    { "value": "18", "label": "18-Truyenthieunhi.net" },
    { "value": "19", "label": "19-infonet.vietnamnet.vn" },
    { "value": "20", "label": "20-soha.vn" },
    { "value": "21", "label": "21-tienphong.vn" },
    { "value": "22", "label": "22-vnreview.vn" },
    { "value": "23", "label": "23-nguoiduatin.vn" },
    { "value": "24", "label": "24-laodong.vn" },
    { "value": "25", "label": "25-baogiaothong.vn" },
    { "value": "26", "label": "26-vtv.vn" },
    { "value": "27", "label": "27-danviet.vn" },
    { "value": "28", "label": "28-vietstock.vn" },
    { "value": "29", "label": "29-nhandan.vn" },
    { "value": "30", "label": "30-thethaovanhoa.vn" },
    { "value": "31", "label": "31-fica.dantri.com.vn" },
    { "value": "32", "label": "32-dtinews.dantri.com.vn" },
    { "value": "33", "label": "33-vtcnews.vn" },
    { "value": "34", "label": "34-vov.gov.vn" },
    { "value": "35", "label": "35-xaluannews.com" },
    { "value": "36", "label": "36-congdankhuyenhoc.vn" },
    { "value": "37", "label": "37-phapluatvacuocsong.vn" },
    { "value": "38", "label": "38-vietnamplus.vn" },
    { "value": "39", "label": "39-giadinhmoi.vn" },
    { "value": "40", "label": "40-kinhtedothi.vn" },
    { "value": "41", "label": "41-tieudung.kinhtedothi.vn" },
    { "value": "42", "label": "42-bongdadoisong.vn" },
    { "value": "43", "label": "43-thanhphohaiphong.gov.vn" },
    { "value": "44", "label": "44-vgt.vn" },
    { "value": "45", "label": "45-vietbao.vn" },
    { "value": "46", "label": "46-dautuvietnam.com.vn" },
    { "value": "47", "label": "47-thegioihoinhap.vn" },
    { "value": "48", "label": "48-vietbao.vn" },
    { "value": "49", "label": "49-vietnambeauty.com.vn" },
    { "value": "50", "label": "50-doisongnet.vn" },
    { "value": "51", "label": "51-www.youtube.com" },
    { "value": "52", "label": "52-doanhnhanduongthoi.com.vn" },
    { "value": "53", "label": "53-www.facebook.com" },
    { "value": "54", "label": "54-doanhnhanduongthoi.com.vn" },
    { "value": "55", "label": "55-dimensions.com.vn" }
];

const extensionID = receivedExtensionID || allowedExtensionID;

// Kiểm tra sự phù hợp giữa extension ID
const isValidExtension = extensionID === allowedExtensionID;

console.log(isValidExtension ? "Extension is valid!" : "Extension is invalid!");

